-- MySQL Script generated by MySQL Workbench
-- 10/29/17 19:42:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gas_shop_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gas_shop_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gas_shop_db` DEFAULT CHARACTER SET utf8 ;
USE `gas_shop_db` ;

-- -----------------------------------------------------
-- Table `gas_shop_db`.`fuels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gas_shop_db`.`fuels` (
  `fuel_id` INT NOT NULL AUTO_INCREMENT,
  `fuel_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`fuel_id`),
  UNIQUE INDEX `fuel_name_UNIQUE` (`fuel_name` ASC),
  UNIQUE INDEX `id_UNIQUE` (`fuel_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gas_shop_db`.`user_profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gas_shop_db`.`user_profiles` (
  `user_profiles_id` INT NOT NULL AUTO_INCREMENT,
  `user_profile_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_profiles_id`),
  UNIQUE INDEX `user_profiles_id_UNIQUE` (`user_profiles_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gas_shop_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gas_shop_db`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `tel` VARCHAR(45) NULL,
  `address` VARCHAR(100) NULL,
  `password` VARCHAR(10) NOT NULL,
  `user_profiles_user_profiles_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `user_profiles_user_profiles_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  INDEX `fk_users_user_profiles1_idx` (`user_profiles_user_profiles_id` ASC),
  CONSTRAINT `fk_users_user_profiles1`
    FOREIGN KEY (`user_profiles_user_profiles_id`)
    REFERENCES `gas_shop_db`.`user_profiles` (`user_profiles_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gas_shop_db`.`gas_stations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gas_shop_db`.`gas_stations` (
  `gas_station_id` INT NOT NULL AUTO_INCREMENT,
  `gas_station_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`gas_station_id`),
  UNIQUE INDEX `gas_station_id_UNIQUE` (`gas_station_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gas_shop_db`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gas_shop_db`.`orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `users_user_id` INT NOT NULL,
  PRIMARY KEY (`order_id`, `users_user_id`),
  UNIQUE INDEX `order_id_UNIQUE` (`order_id` ASC),
  INDEX `fk_orders_users1_idx` (`users_user_id` ASC),
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `gas_shop_db`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gas_shop_db`.`gas_portions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gas_shop_db`.`gas_portions` (
  `gas_portions_id` INT NOT NULL AUTO_INCREMENT,
  `amount` INT NOT NULL,
  `gas_stations_gas_station_id` INT NOT NULL,
  `fuels_id` INT NOT NULL,
  PRIMARY KEY (`gas_portions_id`, `gas_stations_gas_station_id`, `fuels_id`),
  UNIQUE INDEX `gas_portions_id_UNIQUE` (`gas_portions_id` ASC),
  INDEX `fk_gas_portions_gas_stations1_idx` (`gas_stations_gas_station_id` ASC),
  INDEX `fk_gas_portions_fuels1_idx` (`fuels_id` ASC),
  CONSTRAINT `fk_gas_portions_gas_stations1`
    FOREIGN KEY (`gas_stations_gas_station_id`)
    REFERENCES `gas_shop_db`.`gas_stations` (`gas_station_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gas_portions_fuels1`
    FOREIGN KEY (`fuels_id`)
    REFERENCES `gas_shop_db`.`fuels` (`fuel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gas_shop_db`.`orders_has_gas_portions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gas_shop_db`.`orders_has_gas_portions` (
  `orders_order_id` INT NOT NULL,
  `gas_portions_gas_portions_id` INT NOT NULL,
  PRIMARY KEY (`orders_order_id`, `gas_portions_gas_portions_id`),
  INDEX `fk_orders_has_gas_portions_gas_portions1_idx` (`gas_portions_gas_portions_id` ASC),
  INDEX `fk_orders_has_gas_portions_orders1_idx` (`orders_order_id` ASC),
  CONSTRAINT `fk_orders_has_gas_portions_orders1`
    FOREIGN KEY (`orders_order_id`)
    REFERENCES `gas_shop_db`.`orders` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_has_gas_portions_gas_portions1`
    FOREIGN KEY (`gas_portions_gas_portions_id`)
    REFERENCES `gas_shop_db`.`gas_portions` (`gas_portions_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gas_shop_db`.`references`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gas_shop_db`.`references` (
  `reference_id` INT NOT NULL AUTO_INCREMENT,
  `cost` FLOAT NOT NULL,
  `gas_stations_gas_station_id` INT NOT NULL,
  `fuels_id` INT NOT NULL,
  PRIMARY KEY (`reference_id`, `gas_stations_gas_station_id`, `fuels_id`),
  INDEX `fk_references_gas_stations1_idx` (`gas_stations_gas_station_id` ASC),
  INDEX `fk_references_fuels1_idx` (`fuels_id` ASC),
  CONSTRAINT `fk_references_gas_stations1`
    FOREIGN KEY (`gas_stations_gas_station_id`)
    REFERENCES `gas_shop_db`.`gas_stations` (`gas_station_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_references_fuels1`
    FOREIGN KEY (`fuels_id`)
    REFERENCES `gas_shop_db`.`fuels` (`fuel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
